"""Adicionar campo is_admin

Revision ID: 8454debb5cce
Revises: b5a84d76ee15
Create Date: 2026-06-30 15:02:56.291493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8454debb5cce'
down_revision = 'b5a84d76ee15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_antigo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desconto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promocao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('stock')
        batch_op.drop_column('ativo')
        batch_op.drop_column('destaque')
        batch_op.drop_column('promocao')
        batch_op.drop_column('desconto')
        batch_op.drop_column('preco_antigo')

    # ### end Alembic commands ###
