"""Corrigir relacionamento entre utilizador e carrinho

Revision ID: 8c9450e40ad7
Revises: e73ae7f8ee8b
Create Date: 2026-07-14 10:32:51.192596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9450e40ad7'
down_revision = 'e73ae7f8ee8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_produto_id'), ['produto_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cart_items_produto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cart_items_cart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_cart_id_fkey'), 'carts', ['cart_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('cart_items_produto_id_fkey'), 'produtos', ['produto_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_cart_items_produto_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
