"""add reset code fields to users

Revision ID: b5a84d76ee15
Revises: 
Create Date: 2026-06-27 11:25:44.696770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a84d76ee15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('reset_code_expires')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
